# Timeout after 5h. Today, there are around 50 virtual machines in the
# production cluster. It seems to take between 2.5m and 3m for a machine to be
# recreated and for ndt-server or the API to be available. If we update the
# machines serially, this is around 2.5 hours. Set the timeout to double that
# just for room to grow.
timeout: 18000s

steps:
- name: gcr.io/$PROJECT_ID/gcloud-jsonnet-cbif:1.1
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    apt update
    apt install --yes unzip
    curl --remote-name https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
    unzip terraform_1.5.3_linux_amd64.zip
    mv terraform /usr/local/bin/
    export PROJECT=$PROJECT_ID
    bash scripts/tf_apply.sh $$PROJECT
