
#!/bin/sh
# Terraform Import Script generated by gcloud cli


terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-data-processing-ContainerNodePool-us-east1.google_container_node_pool.archive_repacker mlab-sandbox/us-east1/data-processing/archive-repacker
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-data-processing-ContainerNodePool-us-east1.google_container_node_pool.downloader_pool mlab-sandbox/us-east1/data-processing/downloader-pool
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-data-processing-ContainerNodePool-us-east1.google_container_node_pool.parser mlab-sandbox/us-east1/data-processing/parser
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-data-processing-ContainerNodePool-us-east1.google_container_node_pool.prometheus mlab-sandbox/us-east1/data-processing/prometheus
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-data-processing-ContainerNodePool-us-east1.google_container_node_pool.stats_pipeline mlab-sandbox/us-east1/data-processing/stats-pipeline
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-prometheus-federation-ContainerNodePool-us-central1-c.google_container_node_pool.prometheus mlab-sandbox/us-central1-c/prometheus-federation/prometheus
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-prometheus-federation-ContainerNodePool-us-central1-c.google_container_node_pool.static_external_ip mlab-sandbox/us-central1-c/prometheus-federation/static-external-ip
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-us-central1-c.google_container_cluster.prometheus_federation mlab-sandbox/us-central1-c/prometheus-federation
terraform import module.tf-output-projects-mlab-sandbox-ContainerCluster-us-east1.google_container_cluster.data_processing mlab-sandbox/us-east1/data-processing
